##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/atril
    - autoconf-archive
    - clang
    - gcc
    - git
    - gtksourceview4
    - make
    - mate-common
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/atril
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - libgtk-3-dev
    - libgtksourceview-4-dev
    - libpeas-dev
    - libvte-2.91-dev
    - make
    - mate-common
    - pluma-dev
    - python3-dev
    - python-dbus-dev
    - python3-gi
    - yelp-tools
# for building pluma
    - libenchant-2-dev

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/atril.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - dbus-python-devel
    - gcc
    - git
    - gtk3-devel
    - gtksourceview4-devel
    - libpeas-devel
    - make
    - mate-common
    - pluma-devel
    - python3-devel
    - vte291-devel
    - yelp-tools
# for building pluma
    - enchant2-devel
    - iso-codes-devel
    - libSM-devel

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - libgtk-3-dev
    - libgtksourceview-4-dev
    - libpeas-dev
    - libvte-2.91-dev
    - make
    - mate-common
    - pluma-dev
    - python3-dev
    - python-dbus-dev
    - python3-gi
    - yelp-tools
# for building pluma
    - libenchant-2-dev

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'
  - PLUMA_VERSION=1.26.0

before_scripts:
  - cd ${START_DIR}
  - '[ -f pluma-${PLUMA_VERSION}.tar.xz ] || curl -Ls -o pluma-${PLUMA_VERSION}.tar.xz https://github.com/mate-desktop/pluma/releases/download/v${PLUMA_VERSION}/pluma-${PLUMA_VERSION}.tar.xz'
  - tar xf pluma-${PLUMA_VERSION}.tar.xz
  - cd pluma-${PLUMA_VERSION}
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --enable-deprecations --enable-python --enable-verify-all
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude --force -D__cplusplus .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: pluma-plugins-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
